networks:
  vps-consulting-net:
    name: vps-consulting-net
    external: true

services:

  k6-order-race:
    image: grafana/k6
    networks:
      - vps-consulting-net
    volumes:
      - ./k6:/scripts
    environment:
      BASE_URL: http://app-java:8080
      VUS: ${VUS:-30}
      ORDER_AMOUNT: ${ORDER_AMOUNT:-1000}
      CREDIT_LIMIT: ${CREDIT_LIMIT:-10000}
    command: run /scripts/order-credit-race.js

  k6-transaction-race:
    image: grafana/k6
    networks:
      - vps-consulting-net
    volumes:
      - ./k6:/scripts
    environment:
      BASE_URL: http://app-kotlin:8080
      BALANCE_VUS: ${BALANCE_VUS:-30}
      BALANCE_DEBIT_AMOUNT: ${BALANCE_DEBIT_AMOUNT:-1000}
      BALANCE_INITIAL_CREDIT: ${BALANCE_INITIAL_CREDIT:-10000}
      IDEMPOTENCY_VUS: ${IDEMPOTENCY_VUS:-20}
      IDEMPOTENCY_DEBIT_AMOUNT: ${IDEMPOTENCY_DEBIT_AMOUNT:-500}
    command: run /scripts/transaction-credit-race.js
